spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/aki_back'
    username: 'postgres'
    password: 'postgres'
  liquibase:
    enabled: true
  mail:
    host: 'smtp.yandex.ru'
    port: 465
    protocol: 'smtps'
    username: 'example@example.com'
    password: 'password'
    properties:
      mail:
        debug: false
        smtp:
          auth: true
        starttls:
          enable: true
        ssl:
          enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
springdoc:
  swagger-ui:
    path: '/swagger-ui'
aki:
  url: 'http://localhost:8080'
  reset-password-expiration-min: 180
  none-same-site-cookies: false
  data-path: 'data'
  max-file-size-mb: 10
  image-url-prefix: 'data'
  agreement-default-website: 'https://createdin.moscow/'
  security:
    key-secret: 'akicreatedinmoscowlctleaders2023akicreatedinmoscowlctleaders2023'
    auth-token-validity: 1h
    refresh-token-validity: 7d
