spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/aki_back'
    username: 'postgres'
    password: 'Orion123'
  liquibase:
    enabled: true
springdoc:
  swagger-ui:
    path: '/swagger-ui'
