spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/aki_back'
    username: 'postgres'
    password: 'postgres'
  liquibase:
    enabled: true
springdoc:
  swagger-ui:
    path: '/swagger-ui'
aki:
  security:
    key-secret: 'akicreatedinmoscowlctleaders2023akicreatedinmoscowlctleaders2023'
    auth-token-validity: 1h
    refresh-token-validity: 7d
