spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/aki_back'
    username: 'postgres'
    password: 'postgres'
  liquibase:
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
springdoc:
  swagger-ui:
    path: '/swagger-ui'
aki:
  none-same-site-cookies: false
  data-path: 'data'
  max-file-size-mb: 10
  image-url-prefix: 'data'
  security:
    key-secret: 'akicreatedinmoscowlctleaders2023akicreatedinmoscowlctleaders2023'
    auth-token-validity: 1h
    refresh-token-validity: 7d
