ALTER TABLE place
    ALTER COLUMN place_type DROP NOT NULL;

ALTER TABLE place
    DROP COLUMN specialization;

CREATE TYPE SPECIALIZATION_ENUM AS ENUM (
    'FILM_STUDIO', 'GALLERY', 'PUBLISHING_HOUSE', 'BOOKSTORE', 'DESIGN_STUDIO', 'CREATIVE_SPACE',
    'CINEMA', 'SOUND_RECORDING_STUDIO', 'AR_VR_STUDIOS');

ALTER TABLE place
    ADD COLUMN specialization SPECIALIZATION_ENUM ARRAY NOT NULL;
