package moscow.createdin.backend.model.enums

enum class SpecializationType {
    FILM_STUDIO,
    GALLERY,
    PUBLISHING_HOUSE,
    BOOKSTORE,
    DESIGN_STUDIO,
    CREATIVE_SPACE,
    CINEMA,
    SOUND_RECORDING_STUDIO,
    AR_VR_STUDIOS,
    SHOWROOM,
    ART_WORKSHOP,
    PROTOTYPING_CENTER,
    LAYOUT_WORKSHOP,
    RENDERING_STUDIO,
    PHOTO_VIDEO_STUDIO,
    REHEARSAL_ROOM,
    DANCE_HALL,
    STAGE_SPACE,
    VIDEO_EDITING_STUDIO,
    MOKAP_STUDIO,
    SEWING_SHOP,
    SHOW_SPACE,
    MUSIC_REHEARSAL_STUDIO,
    CONCERT_HALL
}
